# Generated by Django 5.0.5 on 2024-05-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quotes',
            new_name='quote',
        ),
    ]
